sudo: required
services:
  - docker

before_install:
  - docker build -t yonatanharel/multi-docker -f ./client/Dockerfile.dev ./client

scripts:
  - docker run yonatanharel/multi-docker npm test -- --coverage

after_success:
  - docker build -t yonatanharel/multi-client ./client
  - docker build -t yonatanharel/multi-nginx ./ngninx
  - docker build -t yonatanharel/multi-server ./server
  - docker build -t yonatanharel/multi-worker ./worker

# Login into Docker CLI
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them into Docker hub
- docker push yonatanharel/multi-client
- docker push yonatanharel/multi-nginx
- docker push yonatanharel/multi-server
- docker push yonatanharel/multi-worker